Traceback (most recent call last):
  File "inverse_PINN_AD_trueY.py", line 578, in <module>
    myprint("log_path: {}".format(opt.log_path), opt.log_path)
  File "/deac/csc/chenGrp/zhanj318/AD_inverse/utils.py", line 9, in wrapper
    with open(args[1], "a") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/test20221017_0.txt/test_1-5.txt'
